export const CONCORRENTES = [
  { loja: '3d Tech', instagram: null, website: null, observacao: 'Cara do youtube do cantinho do café' },
  { loja: 'Decor Impressão 3d', instagram: null, website: null, observacao: null },
  { loja: '3d Unique', instagram: null, website: 'https://3dunique.com.br/', observacao: null },
  { loja: 'Jacob Impressão 3d', instagram: null, website: null, observacao: null },
  { loja: 'VoxPrint 3d', instagram: null, website: null, observacao: null },
  { loja: 'Voxel Lab 3d', instagram: null, website: 'https://voxellab3d.com.br/', observacao: null },
  { loja: 'FS3D Premium', instagram: null, website: null, observacao: null },
  { loja: 'Epic 3d Studio', instagram: null, website: null, observacao: null },
  { loja: 'Cosmyco', instagram: null, website: null, observacao: null },
  { loja: 'Hex3Design', instagram: null, website: null, observacao: null },
  { loja: 'DOM3d', instagram: null, website: null, observacao: null },
  { loja: 'Trekko3d', instagram: null, website: 'trekko3d.com', observacao: null },
  { loja: 'Imalab', instagram: null, website: null, observacao: null },
  { loja: 'GM Utility', instagram: null, website: null, observacao: null },
  { loja: 'PrintEvolut', instagram: null, website: null, observacao: null },
  { loja: 'Migramah', instagram: null, website: null, observacao: null },
  { loja: 'Cebola Roxa', instagram: null, website: null, observacao: 'Só vende suporte pra polaroid' },
  { loja: 'ShopTeem 3D', instagram: null, website: null, observacao: 'Hollyland case' },
  { loja: 'Presentes Criativos 3d', instagram: null, website: null, observacao: 'Suportes, cortadores de biscoitos' },
  { loja: 'Lojinha do Jean', instagram: null, website: null, observacao: 'Cortadores de biscoito' },
  { loja: 'Vf3d', instagram: null, website: null, observacao: 'Organizador de cabo e estojo de Ozempic' },
  { loja: 'Norr3d', instagram: null, website: null, observacao: null },
  { loja: 'Coco_3d', instagram: null, website: null, observacao: null },
  { loja: 'IGT 3d', instagram: null, website: null, observacao: null },
  { loja: 'F1 impressões', instagram: null, website: null, observacao: null },
  { loja: 'Qora Design', instagram: null, website: null, observacao: 'Foco em Abajur' },
  { loja: 'Luvia 3d', instagram: null, website: null, observacao: null },
  { loja: 'Oliwia Creations', instagram: null, website: null, observacao: null },
];
