/**
 * Catálogo inicial de produtos importado da aba "Produtos" da planilha Farm 3D.
 * `filamentoNome` resolve-se para `filamentoId` no seed via lookup por nome.
 *
 * URLs de inspiração e modelo 3D foram extraídas dos hyperlinks reais da
 * planilha (sheet1.xml + sheet1.xml.rels). Na planilha o texto exibido era
 * "Shopee" / "Mercado Livre" / "Maker World" / "Etsy" / "Thangs" como
 * placeholder visual; o link real estava escondido atrás do texto.
 *
 * Unidades:
 *  - pesoG: gramas
 *  - tempoH: horas
 *  - embalagemCentavos / precoCentavos: centavos (R$ * 100)
 */
import type { Canal, Impressora } from '@mahou-hub/contracts';

interface ProdutoSeed {
  nome: string;
  inspiracao: string | null;
  modelo3dUrl: string | null;
  filamentoNome: string;
  pesoG: number;
  tempoH: number;
  impressora: Impressora;
  embalagemCentavos: number;
  precoCentavos: number;
  canalPrincipal: Canal;
}

export const PRODUTOS: ProdutoSeed[] = [
  { nome: 'Organizador de esmalte', inspiracao: 'https://www.mercadolivre.com.br/suporte-expositor-de-esmalte-maquiagem-acrilico-57-degraus/up/MLBU3376557109', modelo3dUrl: 'https://makerworld.com/en/models/1858883-large-nail-polish-organizer?from=search', filamentoNome: 'ABS Branco', pesoG: 417, tempoH: 8, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 4490, canalPrincipal: 'SHOPEE' },
  { nome: 'Chibieren', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 42, tempoH: 2, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2900, canalPrincipal: 'SHOPEE' },
  { nome: 'Onix', inspiracao: 'https://www.mercadolivre.com.br/aro-moldura-retrovisor-onix-2021-a-2026-lado-esquerdo/up/MLBU2974038098', modelo3dUrl: 'https://makerworld.com/pt/models/1686372-vauxhall-opel-astra-h-2010-passenger-wing-mirror?from=search', filamentoNome: 'ABS Branco', pesoG: 95, tempoH: 3, impressora: 'H2C', embalagemCentavos: 200, precoCentavos: 3490, canalPrincipal: 'SHOPEE' },
  { nome: 'Brinco Tanjiro', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 10, tempoH: 1, impressora: 'H2C', embalagemCentavos: 100, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte Para Marcador', inspiracao: 'https://shopee.com.br/Suporte-Organizador-para-Canetas-Marcadoras-Compat%C3%ADvel-com-Touch-Base-caneta-30-a-120-Unidades-i.314505611.23794239101', modelo3dUrl: 'https://makerworld.com/en/models/2132801-marker-holder?from=search', filamentoNome: 'PETG Branco', pesoG: 240, tempoH: 9, impressora: 'A1', embalagemCentavos: 400, precoCentavos: 5990, canalPrincipal: 'SHOPEE' },
  { nome: 'Kit c/3 Suportes de toalha', inspiracao: 'https://shopee.com.br/Cabide-Gancho-Adesivo-de-Parede-com-Fita-Dupla-Face-3M-para-Toalhas-Banheiro-Cor-Preto-Branco-Porta-i.1679576290.58201170380', modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 21, tempoH: 0.75, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de toalha', inspiracao: 'https://shopee.com.br/Cabide-Gancho-Adesivo-de-Parede-com-Fita-Dupla-Face-3M-para-Toalhas-Banheiro-Cor-Preto-Branco-Porta-i.1679576290.58201170380', modelo3dUrl: 'https://makerworld.com/en/models/2124904-wall-hook-coat-hanger-towel-rack?from=search', filamentoNome: 'PETG Branco', pesoG: 7, tempoH: 0.25, impressora: 'A1', embalagemCentavos: 100, precoCentavos: 990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de Papel Toalha', inspiracao: 'https://shopee.com.br/product/988030305/18297892536/', modelo3dUrl: 'https://makerworld.com/en/models/422258-modern-papertowel-kitchen-roll-holder-kuchenrolle?from=search', filamentoNome: 'PETG Branco', pesoG: 100, tempoH: 2.5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2490, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte Carplay', inspiracao: 'https://shopee.com.br/Suporte-De-Barra-Para-Multimidia-Carplay-Mtc-10-Mtc-13-Mtc-15-i.1374226644.22193436486', modelo3dUrl: 'https://makerworld.com/en/models/471754-soporte-carpuride-702-502-para-barra-de-20mm?from=search', filamentoNome: 'ASA Branco', pesoG: 25, tempoH: 1, impressora: 'A1', embalagemCentavos: 500, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Manopla de Cambio', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 60, tempoH: 2, impressora: 'H2C', embalagemCentavos: 200, precoCentavos: 5000, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de Papel Higiênico', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/2069554-modern-toilet-paper-holder-modern-minimalist?from=search', filamentoNome: 'PETG Branco', pesoG: 54, tempoH: 2, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1490, canalPrincipal: 'SHOPEE' },
  { nome: 'Kit c/2 Suportes de Papel Higiênico', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/2069554-modern-toilet-paper-holder-modern-minimalist?from=search', filamentoNome: 'PETG Branco', pesoG: 120, tempoH: 3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de Papel Higiênico c/ bau', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/1636314-compartment-toilet-paper-holder?from=search', filamentoNome: 'PETG Branco', pesoG: 340, tempoH: 9, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 5990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de Papel Higiênico Polaroid', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/1969084-polaroid-style-toilet-paper-holder?from=search', filamentoNome: 'PETG Branco', pesoG: 585, tempoH: 18, impressora: 'H2C', embalagemCentavos: 600, precoCentavos: 12990, canalPrincipal: 'ML' },
  { nome: 'Suporte de papel Higiênico Mario', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/204199-mario-toilet-roll-holder?from=search', filamentoNome: 'PETG Branco', pesoG: 554, tempoH: 21, impressora: 'H2C', embalagemCentavos: 600, precoCentavos: 19900, canalPrincipal: 'ML' },
  { nome: 'Chaveiro container', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/2355322-flower-pill-box-keychain?from=search', filamentoNome: 'PETG Branco', pesoG: 16, tempoH: 1.3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2000, canalPrincipal: 'SHOPEE' },
  { nome: 'Organizador de Remédio', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/204035-pill-box-pill-organizer-7-days-morning-night?from=search', filamentoNome: 'PETG Branco', pesoG: 132, tempoH: 4, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Roda Interativa para gatos', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/1450204-cat-toy?from=search', filamentoNome: 'PETG Branco', pesoG: 129, tempoH: 3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3990, canalPrincipal: 'SHOPEE' },
  { nome: 'Roda Interativa para gatos Wave', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/2587157-cat-toy-wave-donut?from=search', filamentoNome: 'PETG Branco', pesoG: 108, tempoH: 3.4, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3990, canalPrincipal: 'SHOPEE' },
  { nome: 'Roda Interativa para gatos Oval', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/861955-cat-toy-oval', filamentoNome: 'PETG Branco', pesoG: 109, tempoH: 3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3490, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de beço', inspiracao: 'https://shopee.com.br/Suporte-de-Ber%C3%A7o-para-Aparelho-de-Ru%C3%ADdo-Branco-Beb%C3%AA-Ber%C3%A7o-Universal-i.903571416.45155625439', modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 40, tempoH: 2, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1200, canalPrincipal: 'SHOPEE' },
  { nome: 'Organizador de cabo', inspiracao: 'https://shopee.com.br/Organizador-de-cabos-USB-carregadores-organizador-de-mesa-escritorio-i.1737342757.58205198316', modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 269, tempoH: 5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3990, canalPrincipal: 'SHOPEE' },
  { nome: 'Contador de livros lidos', inspiracao: 'https://www.etsy.com/listing/4324158706/personalized-books-read-this-year', modelo3dUrl: 'https://makerworld.com/en/models/1729923-books-read-counter?from=search', filamentoNome: 'PETG Branco', pesoG: 90, tempoH: 5.9, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3490, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte para kindle nuvem', inspiracao: 'https://shopee.com.br/Suporte-para-Kindle-Nuvem-Apoio-de-Leitura-de-Mesa-Fofo-Compat%C3%ADvel-Paperwhite-Oasis-i.1679302159.23899183876', modelo3dUrl: 'https://makerworld.com/en/models/1087083-cloud-kindle-stand?from=search', filamentoNome: 'PETG Branco', pesoG: 90, tempoH: 2.5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte para kindle livro', inspiracao: 'https://shopee.com.br/Suporte-para-Kindle-em-formato-de-livro-Acess%C3%B3rio-para-Kindle-e-e-readers-Presente-liter%C3%A1rio-i.1505748543.22093893885', modelo3dUrl: 'https://makerworld.com/en/models/1863537-book-shaped-kindle-e-reader-stand?from=search', filamentoNome: 'PETG Branco', pesoG: 85, tempoH: 2, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Kit 10 suportes pra fotos', inspiracao: 'https://shopee.com.br/10-Porta-Retrato-Base-Suporte-Apoio-Para-Foto-Polaroide-Cora%C3%A7%C3%A3o-Decora%C3%A7%C3%A3o-Festa-Cart%C3%A3o-Menu-Casamento-Decora%C3%A7%C3%A3o-Festa-i.1275098609.23697761745', modelo3dUrl: 'https://makerworld.com/en/models/1116215-heart-photo-stand?from=search', filamentoNome: 'PLA Branco', pesoG: 31, tempoH: 0.4, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Holyland case', inspiracao: 'https://shopee.com.br/Case-Anti-Impacto-Estojo-3D-para-Microfone-Lark-M2-Hollyland-Duo-i.1183529082.23598866704', modelo3dUrl: 'https://makerworld.com/en/models/1525416-hollyland-lark-m2-combo-case?from=search', filamentoNome: 'PETG Branco', pesoG: 61, tempoH: 2.5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3490, canalPrincipal: 'SHOPEE' },
  { nome: 'Cesta decorativa', inspiracao: 'https://shopee.com.br/Cesto-de-Decora%C3%A7ao-Porta-Objeto-Organizador-de-Mesa-Porta-treco-Decorativo-Moderno-Elegante-i.1183529082.23094409600', modelo3dUrl: 'https://makerworld.com/en/models/1309907-modern-catch-all-centerpiece-bowl-filte', filamentoNome: 'PETG Branco', pesoG: 110, tempoH: 6, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 3500, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte Óculos gatinho', inspiracao: 'https://shopee.com.br/Gatinho-Suporte-para-%C3%93culos-Base-para-%C3%B3culos-Porta-%C3%B3culos-decorativo-i.1306060436.23897833882', modelo3dUrl: 'https://makerworld.com/en/models/2390692-cat-eye-glass-holder-cute-two-sizes?from=search', filamentoNome: 'ABS Branco', pesoG: 120, tempoH: 3.3, impressora: 'H2C', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Placa com o nome  Minecraft', inspiracao: 'https://shopee.com.br/Nome-Personalizado-em-3D-%E2%80%93-Escolha-o-Seu-Placa-Decorativa-para-Quartos-Festas-e-Presentes-i.1388814327.23994326073', modelo3dUrl: 'https://makerworld.com/en/models/1969808-custom-minecraft-name-plate?from=search', filamentoNome: 'PETG Branco', pesoG: 80, tempoH: 4, impressora: 'A1', embalagemCentavos: 300, precoCentavos: 3490, canalPrincipal: 'SHOPEE' },
  { nome: 'Placa com o nome', inspiracao: 'https://shopee.com.br/Nome-Personalizado-em-3D-%E2%80%93-Escolha-o-Seu-Placa-Decorativa-para-Quartos-Festas-e-Presentes-i.1388814327.23994326073', modelo3dUrl: 'https://makerworld.com/en/models/2422974-custom-name?from=search', filamentoNome: 'PETG Branco', pesoG: 22, tempoH: 2, impressora: 'A1', embalagemCentavos: 300, precoCentavos: 3000, canalPrincipal: 'SHOPEE' },
  { nome: 'Estojo de Insulina', inspiracao: 'https://shopee.com.br/Estojo-para-caneta-de-insulina-azempic-mounjaro-i.1737342757.58205177166', modelo3dUrl: 'https://makerworld.com/en/models/2242952-dual-insulin-peptide-pen-case-print-in-place', filamentoNome: 'PETG Branco', pesoG: 100, tempoH: 3.7, impressora: 'A1', embalagemCentavos: 300, precoCentavos: 3990, canalPrincipal: 'SHOPEE' },
  { nome: 'Abajur de Ondas', inspiracao: 'https://shopee.com.br/Lumin%C3%A1ria-e-Abajur-Mini-Nuvem-para-Mesa-Quarto-Escrit%C3%B3rio-com-L%C3%A2mpada-LED-i.464808753.22594308901', modelo3dUrl: 'https://makerworld.com/en/models/2321044-wave-minimalist-lamp?from=search', filamentoNome: 'PETG Branco', pesoG: 82, tempoH: 5.2, impressora: 'A1', embalagemCentavos: 800, precoCentavos: 5990, canalPrincipal: 'SHOPEE' },
  { nome: 'Abajur Nuvem', inspiracao: 'https://shopee.com.br/Lumin%C3%A1ria-e-Abajur-Mini-Nuvem-para-Mesa-Quarto-Escrit%C3%B3rio-com-L%C3%A2mpada-LED-i.464808753.22594308901', modelo3dUrl: 'https://makerworld.com/en/models/2253791-wavy-cloud-lamp-modular-strala-modu-series?from=search', filamentoNome: 'PETG Branco', pesoG: 100, tempoH: 6, impressora: 'A1', embalagemCentavos: 800, precoCentavos: 5990, canalPrincipal: 'SHOPEE' },
  { nome: 'Porta Aliança', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/1040629-heart-ring-box-print-in-place?from=search', filamentoNome: 'PETG Branco', pesoG: 22, tempoH: 1.3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Marca Página Quarta asa', inspiracao: 'https://shopee.com.br/Quarta-Asa-Marcador-de-P%C3%A1gina-Fourth-Wing-Vazado-FW09-Inspirado-no-Mundo-de-Quarta-Asa-3D-PLA-Ecol%C3%B3gico-14cm-x-15cm-x-3m-i.803811450.19699602072', modelo3dUrl: 'https://makerworld.com/en/models/1007648-fourth-wing-bookmark-tairn-and-andarna?from=search', filamentoNome: 'PETG Branco', pesoG: 16, tempoH: 0.6, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Dragaozinho "Quarta Asa"', inspiracao: 'https://shopee.com.br/Miniatura-Andarna-Beb%C3%AA-Drag%C3%A3o-Dourado-com-Ovo-Quarta-Asa-Fourth-Wing-Tempestade-de-Onix-Decora%C3%A7%C3%A3o-i.803811450.22293721858', modelo3dUrl: 'https://makerworld.com/en/models/1035037-dragon-egg-with-baby-dragon', filamentoNome: 'PETG Branco', pesoG: 35, tempoH: 1.8, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Figure Dragão quarta asa', inspiracao: 'https://shopee.com.br/Quarta-Asa-Tairn-Miniatura-Fourth-Wing-FW12-i.803811450.23398212024', modelo3dUrl: 'https://makerworld.com/en/models/2414345-fourth-wing-tairn-dragon-black-morningstartail?from=search', filamentoNome: 'PETG Branco', pesoG: 70, tempoH: 7, impressora: 'A1', embalagemCentavos: 400, precoCentavos: 4990, canalPrincipal: 'SHOPEE' },
  { nome: 'Love Book', inspiracao: null, modelo3dUrl: 'https://thangs.com/designer/af_inventions/3d-model/LOVE%20BOOK%20%7C%20PHOTO%20ALBUM-1504890', filamentoNome: 'PETG Branco', pesoG: 360, tempoH: 11, impressora: 'A1', embalagemCentavos: 600, precoCentavos: 9900, canalPrincipal: 'ML' },
  { nome: 'Cubo de memoria', inspiracao: null, modelo3dUrl: 'https://thangs.com/designer/af_inventions/3d-model/MEMORY%20CUBE%20%7C%20MAGNETIC%20PHOTO%20CUBE-1543617', filamentoNome: 'PETG Branco', pesoG: 260, tempoH: 6, impressora: 'A1', embalagemCentavos: 600, precoCentavos: 9900, canalPrincipal: 'ML' },
  { nome: 'Cubo de memoria  + 5 pins 10 fotos', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 200, tempoH: 6.5, impressora: 'A1', embalagemCentavos: 2100, precoCentavos: 11990, canalPrincipal: 'ML' },
  { nome: 'Cubo de memoria  + 5 pins 14 fotos', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 250, tempoH: 8.5, impressora: 'A1', embalagemCentavos: 2350, precoCentavos: 14990, canalPrincipal: 'ML' },
  { nome: 'Cubo de memoria  + 5 pins 18 fotos', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 300, tempoH: 10.5, impressora: 'A1', embalagemCentavos: 3450, precoCentavos: 19990, canalPrincipal: 'ML' },
  { nome: 'Suporte Placa de Video', inspiracao: 'https://shopee.com.br/Suporte-Ajust%C3%A1vel-Placa-de-V%C3%ADdeo-GPU-4cm-6cm-Vertical-Universal-i.884180524.22998858368', modelo3dUrl: 'https://makerworld.com/en/models/1574539-adjustable-gpu-support-nvidia-radeon?from=search', filamentoNome: 'PETG Branco', pesoG: 16, tempoH: 1.3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Cortador de biscoitos 4 pokemons', inspiracao: null, modelo3dUrl: 'https://makerworld.com/en/models/990319-pikachu-cookie-cutter?from=search', filamentoNome: 'PETG Branco', pesoG: 42, tempoH: 1.45, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Cortador de biscoito copa', inspiracao: 'https://shopee.com.br/Kit-6-Cortador-Marcador-Cookie-Copa-Do-Mundo-2026-i.884180524.58203097805', modelo3dUrl: 'https://makerworld.com/en/models/2735475-fifa-world-cup-soccer-cookie-cutter-set?from=search', filamentoNome: 'PETG Branco', pesoG: 46, tempoH: 1.5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 1990, canalPrincipal: 'SHOPEE' },
  { nome: 'Cortador de biscoito Patrulha Canina', inspiracao: 'https://shopee.com.br/Kit-Cortadores-de-Biscoito-Patrulha-Canina-7-Modelos-i.1556861546.55757702039', modelo3dUrl: 'https://makerworld.com/en/models/409390-paw-patrol-cookie-cutter?from=search', filamentoNome: 'PETG Branco', pesoG: 90, tempoH: 3.3, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte de Controle PS5 + Fone ps5', inspiracao: 'https://shopee.com.br/Suporte-Porta-Controle-Videogame-Gamer-Para-Ps4-Xbox-Ps5-i.437195453.9478115936', modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 250, tempoH: 5, impressora: 'A1', embalagemCentavos: 1000, precoCentavos: 6990, canalPrincipal: 'SHOPEE' },
  { nome: 'Suporte para Móbile de bebê', inspiracao: null, modelo3dUrl: null, filamentoNome: 'PETG Branco', pesoG: 120, tempoH: 5, impressora: 'A1', embalagemCentavos: 200, precoCentavos: 2990, canalPrincipal: 'SHOPEE' },
];
